#include <string>
#include <vector>
#include <memory>
#include <iostream>
#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <unordered_map>
#include <filesystem>
#include <chrono>
#include <thread>
#include <mutex>
#include <typeindex>

#include "core/Base.h"
#include "core/Layer.h"
#include "core/Event.h"
#include "core/EventBus.h"